### ISSUE TITLE
Using new build system from v2025.5.0.rc1, receive errors when building amuse/ amuse-framework

### ISSUE THREAD

**Issue by bbanne** [amusecode/amuse#1158]
When attempting to build the amuse packages in a new conda env (called amuse), I am receiving errors during the outlined process. I will include files with terminal and logs, but the summary is that I created and activated a new conda env, installed the dependencies as outlined in the build instructions and the output of the setup script, but when I go to run ./setup install all, I receive the following error: 

```
--------------------------------------------------------------------------
The Open MPI wrapper compiler was unable to find the specified compiler
x86_64-conda_cos6-linux-gnu-cc in your PATH.

Note that this compiler was either specified at configure time or in
one of several possible environment variables.
--------------------------------------------------------------------------
make[1]: *** [support/shared/lib-targets.mk:103: amuse_mpi.mo] Error 1
make[1]: Leaving directory '/opt/amuse/amuse-2025.5.0.rc1/lib/amuse_mpi'
make: *** [Makefile:17: amuse_mpi] Error 2
make: Leaving directory '/opt/amuse/amuse-2025.5.0.rc1/lib'
support/setup/installing.sh: line 98: ../support/logs/install-amuse-framework.exit_code: No such file or directory
cat: support/logs/install-amuse-framework.exit_code: No such file or directory

amuse-framework failed to build and install correctly.

This is not supposed to happen!

Please contact the developers on Slack or make an issue on GitHub,
so that we can fix this together.
```

I definitely have the prerequisites installed, and the env active, so if there was something else I needed to change as far en environment variables before beginning the installation, it wasn't included in either the docs or the setup script process. 

Our environment is rhel 8.10 with a conda version of 24.7.1. I've included output from the setup and install process, install logs, and the listing of all packages installed in our conda environment. Any additional guidance is appreciated. I am sure it is probably something I have missed.

[TerminalOutputAmuse.txt](https://github.com/user-attachments/files/20890414/TerminalOutputAmuse.txt)
[CondaEnvAmuse.txt](https://github.com/user-attachments/files/20890415/CondaEnvAmuse.txt)

**Comment by LourensVeen** [comment]
Ah, apologies, yes it is but we had an issue building from tar archives.

What you've got there is actually not a clone, which is a copy of a git repository including git metadata, but an archive, which just contains the files stored in that repository without any git stuff. The AMUSE build system determines which version we're building from the git metadata, and an archive doesn't contain that, so it fails.

I've added a fix for this in v2025.5.0.rc2 a couple weeks ago, so downloading that instead should fix it. It's a bit of a work in progress, fixing #1157 may change how it works again internally but that won't make a difference to users, only to developers.

Sorry for the mess, I think we're almost there with this new build system but it still has some teething issues, as you've unfortunately discovered :frowning:.

**Comment by risojevicv** [comment]
Unfortunately, the shallow clone problem persists in v2025.5.0.rc2. However, when I clone the repo, `git clone https://github.com/amusecode/amuse.git`, I can install amuse-framework and majority of packages.

I ran into problems with amuse-seba. In `src/amuse_seba/toolbox.patch` I had to change 
`-CXXFLAGS  += -I./include -I./include/star -DHAVE_CONFIG_H -DTOOLBOX`
to
`-CXXFLAGS  += -I./include -I./include/star -DHAVE_CONFIG_H -DTOOLBOX -Wconversion`.
After that, the build process started, but failed with
`/home/vlado/anaconda3/envs/amuse/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find src/node/libnode.a: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:53: seba_worker] Error 1`
Apparently, `src/node/libnode.a` library is missing.

**Comment by LourensVeen** [comment]
Interesting, I just tried and I can build successfully from the `v2025.5.0.rc2.tar.gz` file. Could you paste the contents of the `VERSION` file in the top `amuse-2025.5.0.rc2` directory? It should read
```
# This file is used to record the version of AMUSE in a .tar.gz archive made using git
# archive. The build system will pick it up from here if it is not building from a git
# repository but from that tar.gz file.

v2025.5.0.rc2
```

As for the SeBa issue, I can't reproduce it. I made a separate issue for that at #1159, maybe you can paste the whole build log as explained there? It's clear that `libnode.a` is missing, but we need to know why and that's in that log somewhere. Thanks!

**Comment by LourensVeen** [comment]
Ha! That took a bit of figuring out, but I think I've found the problem: the code that looks for the VERSION file actually looks in the wrong location. I somehow had a VERSION file in that wrong location when I tested things, so it worked for me, but for the wrong reasons. So rc2 is still broken. I'll go and apply a fix and we'll do an rc3. And maybe I should add a CI run that tests installing from a tarball, while I'm working on that...

**Comment by LourensVeen** [comment]
Hi again, sorry the the long delay, I'm juggling way too many balls at the moment. But I've made some progress!

The SeBa issue should have been taken care of by #1160. I've made a new PR (#1167) that fixes the VERSION file problem and adds `--channel-override` to the conda command to hopefully help avoid mixed package sources if you're using a pre-existing environment. It also hopefully fixes the version problem properly this time.

I'll make an rc3 as soon as that is merged, and then we can try again.

I think you've got a working install now though using the git clone? In that case feel free to call it good enough, but please  let me know so I can close this issue when #1167 is merged.

**Comment by LourensVeen** [comment]
Coming back to this, I think the issues actually got fixed, but I lost track of this issue and with everyone having a working install I guess it got abandoned.

We have the SeBa PR merged, the `--override-channels` option was added and on top of that `./setup` now detects a split-channels situation and warns about it, with instructions on how to fix the repo, and the build-from-tarball problem has been identified and fixed.

So I'm going to close this issue. Please open a new one if you run into any problem again.
