### ISSUE TITLE
source release missing support3 directory

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#181]
see the issue #180 - I wonder if the ommission is intentional? in any case either it should be included, or the configure script fixed (it still assumes the support3 directory to be present...)

**Comment by ipelupessy** [comment]
it may only be the release on the amuse website...

**Comment by arjenve** [comment]
The release on the github site is "just" a packaging of a specific tag (github does this automagically, i.e.
it makes a tar.gz file of the directory contents). 
While the release on the amuse site is a source distribution made with the python distribution software, unfortunately this was missing a directory.
I fixed the file and release is running...

**Comment by arjenve** [comment]
updated the release (latests is now 11.1!)

**Comment by ipelupessy** [comment]
it still missing/ complains about the support3/configpy.in file...

**Comment by ipelupessy** [comment]
fixed now
