### ISSUE TITLE
AMUSE installation issues

### ISSUE THREAD

**Issue by stevemcmillan** [amusecode/amuse#513]
Some (minor) comments on the new installation procedures and possible errors.

1. I could not get pip install amuse to work.  It ran with no output for a long time, then exited with what looked like compilation errors.  I am using Ubuntu 16.  My student also ran into similar problems, also on Ubuntu.  There were some package build errors (see below) which may have been to blame, but the lack of feedback is bad even if the build succeeds.

2. When I used pip to install the prerequisites, then the traditional 'configure; make all' worked well.  At the very least, this option should be mentioned in the installation instructions.

3. The instructions conflate the installation with a particular choice of environment management, by instructing the user to set up and use a virtual environment.  This may or may not be a good thing to do, but it has nothing to do with installing AMUSE.  I think the installation instructions should be kept separate from housekeeping advice.

4. Galaxia failed to build for me because I didn't have lapack.  I had to run 'sudo apt-get install libblas-dev liblapack-dev', after which the build succeeded.  This should be on the prerequisites list. 

5. I could not get simplex to install -- despite my having installed the hdf5 libraries listed on the amuse code page, the build failed with

/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5

6. I think there is a bug in the ph4/src Makefile.  When I build ph4 from the amuse directory, it succeeds because AMUSE_DIR is explicitly set.  But if I say 'make clean all' in the ph4 directory the src Makefile picks up AMUSE_DIR = ../../../.. which is wrong.  I didn't write that part of the Makefile, and I am hesitant to change it in case I am missing something obvious (other than the fact that maybe I shouldn't be building directly in the source directory, although this is a standard Linux MO).

**Comment by ipelupessy** [comment]
ok, thanks! Will take this into account when redoing the doc..

 regarding point 6:
yes, the way AMUSE_DIR is defined is a common error, it should be either of:
```
AMUSE_DIR?=$(realpath ../../../..)
AMUSE_DIR?=$(shell amusifier --get-amuse-dir)
```

**Comment by stevemcmillan** [comment]
OK.  What is amusifier, exactly?

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by rieder** [comment]
amusifier is the successor to the old build.py script.

**Comment by ipelupessy** [comment]
it had to change name to something less generic for installs...and there is scope to increase its functionality (beyond the build tool)

**Comment by ipelupessy** [comment]
you can use the 
```
AMUSE_DIR?=$(shell amusifier --get-amuse-dir)
```
variant in case you have your code somewhere else outside amuse (note you don't have to set any environment variables either)

**Comment by ipelupessy** [comment]
btw @stevemcmillan the current recommended way to install amuse as developer is to run:
```
pip install -e .
make
```
in a checkout of the repository..(development install means that the python libs etc are linked to the files in the repository)

**Comment by ipelupessy** [comment]
this is also possible for python 3, but you must use the python3 branch: this is fully functional now (ofcourse report any issues!!)

**Comment by rieder** [comment]
> 1. I could not get pip install amuse to work.  It ran with no output for a long time, then exited with what looked like compilation errors.  I am using Ubuntu 16.  My student also ran into similar problems, also on Ubuntu.  There were some package build errors (see below) which may have been to blame, but the lack of feedback is bad even if the build succeeds.

Yes, this isn't ideal. `pip install amuse` tries to first build all the amuse packages, and fails if any of these can't be built. I'm not sure how to solve this yet, except maybe we should not advertise `pip install amuse` as the way to go - e.g. `pip install amuse-$CODE` would probably be better since few people require every single community code immediately.

> 2. When I used pip to install the prerequisites, then the traditional 'configure; make all' worked well.  At the very least, this option should be mentioned in the installation instructions.

This works but this should be exactly the same as running the `pip install -e .` option Inti mentioned. Which I think is preferable since this way the installation is managed and no messing around setting PATHs is needed.

> 3. The instructions conflate the installation with a particular choice of environment management, by instructing the user to set up and use a virtual environment.  This may or may not be a good thing to do, but it has nothing to do with installing AMUSE.  I think the installation instructions should be kept separate from housekeeping advice.

I've added "Optional" to this installation step.

> 4. Galaxia failed to build for me because I didn't have lapack.  I had to run 'sudo apt-get install libblas-dev liblapack-dev', after which the build succeeded.  This should be on the prerequisites list.

It may be that lapack is installed by some other prerequisite as I didn't experience this myself. Will check.

> 5. I could not get simplex to install -- despite my having installed the hdf5 libraries listed on the amuse code page, the build failed with
> 
> /usr/bin/ld: cannot find -lhdf5_hl
> /usr/bin/ld: cannot find -lhdf5
> 

Hmm, this should have been fixed (#453)...

**Comment by MJCWilhelm** [comment]
I ran into similar issues when installing amuse on a fresh Ubuntu 18 install. The Galaxia issue was indeed solved by installing lapack, but SimpleX still fails to install (even with amuse 13.0). For me it fails at building the wheel for SimpleX, but does not give more information (so it does not say it cannot find -lhdf5).

**Comment by ipelupessy** [comment]
@MJCWilhelm are you sure its not the c++ bindings issue? By default on a lot of recent openmpi distributions its not enabled; you would have to compile it (openmpi, or mpich) yourself to enable the c++ MPI bindings..

**Comment by ipelupessy** [comment]
this is issue #446 btw

**Comment by ipelupessy** [comment]
there is  PR #542 for #446

**Comment by ipelupessy** [comment]
the libraries have been mentioned elsewhere, I think this is substantially fixed.
