### ISSUE TITLE
BHTree pip installation issues 

### ISSUE THREAD

**Issue by luk7715** [amusecode/amuse#990]
**Describe the bug**
I tried to install amuse-bhtree with pip but it didn't work.

**To Reproduce**
pip install amuse-bhtree

**Expected behavior**
I expect amuse-bhtree to install and work. 

**Logs**
[bhtree-bug.txt](https://github.com/amusecode/amuse/files/12803385/bhtree-bug.txt)

**Environment (please complete the following information):**
WSL2 and ubuntu 

[bhtree-bug.txt](https://github.com/amusecode/amuse/files/12803385/bhtree-bug.txt)

**Comment by GijsVermarien** [comment]
Seems to also be an issue for the building of the release candidate for some reason? https://www.piwheels.org/logs/0000/1092/1090.txt

**Comment by rieder** [comment]
Yes. I suspect it is due to a newer version of setuptools_scm.

**Comment by luk7715** [comment]
> Could you try installing setuptools_scm==7.1.0 and then retrying amuse-bhtree?

My version of setuptools_scm is 7.1.0, tried to uninstall and reinstall it but the pip install for amuse-bhtree is still failing

**Comment by rieder** [comment]
I found the problem, it indeed has to do with setuptools_scm. I think building AMUSE will still use the newer version, which is annoying. I am preparing an updated release of amuse.

**Comment by rieder** [comment]
2023.10.0rc2 should fix the issue, uploading now.

**Comment by rieder** [comment]
Can you confirm that `pip install --upgrade --pre amuse-framework amuse-bhtree` fixes the problem?

**Comment by luk7715** [comment]
> Can you confirm that `pip install --upgrade --pre amuse-framework amuse-bhtree` fixes the problem?

That worked when I created a new environment. 

However, when I tried the same command in my working environment with the other parts of AMUSE (Hermite, SeBa, Fi, etc.) installed and functional, BHTree still failed to build. 

Here's the log
[bhtree-not-build.txt](https://github.com/amusecode/amuse/files/12810211/bhtree-not-build.txt)

**Comment by rieder** [comment]
The log is empty?
I think it may be related to cached builds though (it's a bit complicated).
You may have to uninstall the old amuse packages first, then install amuse-framework and then the other packages.
I'm sure the original bug is fixed now, but in doing so I created a minor new bug (the version reported by the various community codes is incorrect) that I'm fixing now - will be done in the final 2023.10.0 release, hopefully today.

**Comment by rieder** [comment]
2023.10.0 now released, please upgrade the framework with `pip install --upgrade amuse-framework`
